import { ROUTES } from '@/router/constants';
import type { WidgetType } from '../types/types';

export const WIDGET_ROUTE_MAP: Record<WidgetType, string> = {
  QUIZ: ROUTES.QUIZ_PAGE,
  TRUE_FALSE: ROUTES.TRUE_FALSE_PAGE,
  TASK_RESOLVER: ROUTES.TASK_RESOLVER_PAGE,
  THEORY_HUB: ROUTES.THEORY_HUB_PAGE,
  OUTPUT_PREDICTOR: ROUTES.OUTPUT_PREDICATOR_PAGE,
  BOSS_BATTLE: ROUTES.BOSS_BATTLE_PAGE,
  ERROR_SCANNER: ROUTES.ERROR_SCANNER_PAGE,
};
